### ISSUE TITLE
Hash option not displaying in Arena

### ISSUE THREAD

**Issue by tonymokonen** [sgriffin53/raven#18]
When I install Raven 0.30 in Arena, it does not display the hash option.  I notice that when I issue a uci command, Raven outputs:

uci
id name Raven 0.30
id author Steve Griffin
uciok
option name Hash type spin default 32 min 32 max 256

The uciok should be the last item to be printed.  Otherwise the GUI gets confused.

**Comment by sgriffin53** [comment]
Hi,

Thanks for bringing this to my attention. I've changed the uci output so that uciok is printed last. Hopefully this should fix the hash option issue with Arena.

Thanks,
Steve

**Comment by tonymokonen** [comment]
Hi Steve,
The hash option now displays in Arena.  Thank you for your prompt response.
Tony

    On Saturday, May 4, 2019, 10:57:11 a.m. PDT, sgriffin53 <notifications@github.com> wrote:  
 
 
Hi,

Thanks for bringing this to my attention. I've changed the uci output so that uciok is printed last. Hopefully this should fix the hash option issue with Arena.

Thanks,
Steve
