### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by KierenP** [sgriffin53/raven#19]
https://github.com/sgriffin53/raven/blob/5a2435b16f194c85e273aa8d9ffee82884cd29b0/eval.c#L1015

Hi, I was looking though your code and I came across this like which I believe has a mistake. It should say BN instead of WN

**Comment by sgriffin53** [comment]
Thanks for spotting the typo, Kieren. I've changed it to BN now.

Ideally this would've been picked up by my colour flipping test, but KNNK vs KNNKP obviously wasn't covered in my test positions.
