### ISSUE TITLE
Raven 1.20 error when playing white

### ISSUE THREAD

**Issue by tissatussa** [sgriffin53/raven#22]
hi, i managed to compile Raven v1.20 on Linux (Xubuntu 20.04) by normal make, although i had some warnings. In CuteChess it plays well with Black, but not with White : CuteChess immediately gives 0-1 after Raven gives a best move (which is not displayed on the board). This occurs without entering a FEN (= start position) and also when a FEN is entered (eg. start position).  The CuteChess debug log shows no info which can help.

**Comment by sgriffin53** [comment]
Thanks for reporting this. I'm unable to get Ubuntu running on my PC at the moment but could you please try these commands on your compile of raven and tell me the output:

Run raven and type:

position startpos
go wtime 10000 btime 10000

Then run raven again and type:

position startpos moves e2e4 e7e5
go wtime 10000 btime 10000

I just want to check that it's giving sane output when it's white turn to move on your version.

Once I get Ubuntu running on my PC I'll see if I can reproduce the problem.

Thanks.

**Comment by tissatussa** [comment]
```
tissatussa@tissatussa-HP-Elite-x2-1012-G2:~/Apps/ChessEngines/Raven$ ./raven_v1.20_compiled 
uci
id name Raven 1.20
id author Steve Griffin
option name Hash type spin default 32 min 32 max 256
uciok
position startpos
go wtime 10000 btime 10000
info depth 1 seldepth 2 nodes 45 time 0 score cp 61 pv g1f3
Segmentation fault (core dumped)
tissatussa@tissatussa-HP-Elite-x2-1012-G2:~/Apps/ChessEngines/Raven$ ./raven_v1.20_compiled 
uci
id name Raven 1.20
id author Steve Griffin
option name Hash type spin default 32 min 32 max 256
uciok
position startpos moves e2e4 e7e5
go wtime 10000 btime 10000
info depth 1 seldepth 4 nodes 59 time 0 score cp 51 pv g1f3
info depth 2 seldepth 8 nodes 342 time 1 nps 342000 score cp 27 pv d2d4 b8c6
info depth 3 seldepth 8 nodes 1605 time 2 nps 802500 score cp 27 pv g1f3 g8f6 d2d4
info depth 4 seldepth 11 nodes 2678 time 4 nps 669500 score cp 24 pv g1f3 g8f6 d2d4 f8b4
info depth 5 seldepth 12 nodes 6963 time 8 nps 870375 score cp 47 pv g1f3 b8c6 d2d4 e5d4 f3d4
info depth 6 seldepth 15 nodes 12532 time 15 nps 835466 score cp 45 pv g1f3 b8c6 d2d4 e5d4 f3d4 c6d4
info depth 7 seldepth 17 nodes 29211 time 35 nps 834599 score cp 33 pv g1f3 b8c6 f1c4 g8f6 b1c3 f8c5 e1g1
info depth 8 seldepth 19 nodes 47300 time 61 nps 775409 score cp 39 pv g1f3 b8c6 b1c3 g8f6 d2d4 e5d4 f3d4 f8d6
info depth 9 seldepth 22 nodes 85672 time 119 nps 719932 score cp 29 pv g1f3 b8c6 b1c3 g8f6 d2d4 e5d4 f3d4 f8b4 d4f5
info depth 10 seldepth 23 nodes 196406 time 249 nps 788779 score cp 24 pv g1f3 b8c6 b1c3 g8f6 f1c4 f8c5 d2d3 e8g8 c1g5 a7a6
info time 400
bestmove g1f3
```

**Comment by tissatussa** [comment]
i compiled the same (?!) source on Xubuntu 21.10 (and on the same notebook) and Raven v1.20 does NOT have problems .. so this issue is "solved" .. i don't know the cause, it's just fixed! Hope this will help anyone.

**Comment by sgriffin53** [comment]
Thanks for letting me know. Seems like the issue must be limited to 20.04.

**Comment by sgriffin53** [comment]
Thanks for letting me know. Seems like the issue must be limited to 20.04.
