### ISSUE TITLE
Raven 0.12

### ISSUE THREAD

**Issue by SLW2K** [sgriffin53/raven#26]
I really enjoy & find Raven 0.12 useful. I was wondering if you would do a version that allowed you to select ply depths of 1-8?

Shawn

**Comment by sgriffin53** [comment]
Hi,

There are no plans to make Raven customisable to different playing strengths right now, however I might consider this for future versions.

If you're able to compile raven yourself, you can change the MAX_DEPTH on line 23 of search.c here: https://github.com/sgriffin53/raven/blob/336389ca4236d75a9e0fec0389eb99c05d4cd7c0/search.c#L23

#define MAX_DEPTH 100

If you change 100 to 8, it will search to a maximum of depth 8.

You'll need to compile raven from source after making the change.

I may make play strength customisable using UCI options in the future but there are no plans to do so right now. Thanks.
