### ISSUE TITLE
raven 0.30

### ISSUE THREAD

**Issue by laripette** [sgriffin53/raven#27]
Good morning,

version 0.30 for linux does not work.

the engine crashes, it always stops playing at the beginning or middle of the game.

**Comment by sgriffin53** [comment]
Hi,

Sorry about this. Raven 0.30 was the first version I made and was never tested on Linux. I'd advise using newer versions of Raven as some of the older versions have problems with Linux.

Thanks for bringing this to my attention.

**Comment by laripette** [comment]
Will the problems be corrected or will these old versions of the engine be abandoned ?

**Comment by sgriffin53** [comment]
Most likely I won't be doing any further updates on the older versions of raven, sorry.
